name: bean_there
repository: https://github.com/JoseAlba/bean_there

packages:
  - .
  - widgetbook/

command:
  bootstrap:
    environment:
      flutter: ^3.27.2
      sdk: ^3.6.1

    dependencies:
      flutter:
        sdk: flutter
      flutter_localizations:
        sdk: flutter
      cupertino_icons: 1.0.8
      flutter_card_swiper: ^7.0.2
      flutter_screenutil: 5.9.3
      go_router: 14.7.2
      http: 1.3.0
      path_provider: 2.1.5
      provider: 6.1.2
      rive: 0.13.20
      share_plus: 10.1.4
      shared_preferences: 2.5.1
      uuid: 4.5.1
      widgetbook: 3.10.2
      widgetbook_annotation: 3.2.0

    dev_dependencies:
      flutter_test:
        sdk: flutter
      build_runner: 2.4.14
      flutter_lints: 5.0.0
      melos: 6.3.2
      mockito: 5.4.5
      patrol: 3.14.0
      widgetbook_generator: 3.9.1

scripts:
  build-runner:all:
    run: melos run build-runner --no-select
    description: Run builder runner where available.

  build-runner:
    run: melos exec -c 6 --fail-fast -- flutter pub run build_runner build -d
    packageFilters:
      dependsOn: build_runner
    description: Delete old generated files and create new ones.

  gen-l10n:all:
    run: melos run gen-l10n --no-select
    description: Generate localization files where available.

  gen-l10n:
    run: melos exec -c 6 --fail-fast -- flutter gen-l10n
    packageFilters:
      dependsOn: flutter_localizations
    description: Generate localization files for project.

  integration_developer_mode:
    run: melos exec -c 6 --fail-fast -- patrol develop --target integration_test/end_to_end_test.dart
    packageFilters:
      dirExists:
        - integration_test
    description: Run integration developer mode.

  test-unit:all:
    run: melos run test-unit --no-select
    description: Run all unit tests available.

  test-unit:
    run: melos exec -c 6 --fail-fast -- flutter test
    packageFilters:
      dirExists:
        - test
    description: Run `flutter test` for a specific package.

