name: bean_there
description: Discover and share coffee experiences
repository: https://github.com/JoseAlba/bean_there
version: 0.0.1
publish_to: none

environment:
  flutter: ^3.27.2
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  design_system:
    path: packages/design_system
  image_repository:
    path: packages/image_repository
  cupertino_icons: 1.0.8
  equatable: 2.0.7
  flutter_bloc: 9.0.0
  flutter_card_swiper: ^7.0.2
  go_router: 14.7.2
  http: 1.3.0
  path_provider: 2.1.5
  provider: 6.1.2
  rive: 0.13.20
  share_plus: 10.1.4
  shared_preferences: 2.5.1
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.14
  flutter_lints: 5.0.0
  melos: 6.3.2
  mockito: 5.4.5
  patrol: 3.14.0

flutter:
  assets:
    - assets/animations/
    - .env
  fonts:
    - family: HennyPenny
      fonts:
        - asset: assets/fonts/HennyPenny-Regular.ttf
          weight: 400
  generate: true
  uses-material-design: true
